### ISSUE TITLE
Won't build on Mac OS X

### ISSUE THREAD

**Issue by dhbahn** [monai/node-imagesearch#6]
On my Mac, npm install imagesearch build errors.

bahn (master *) urang $ node --version
v10.8.0
bahn (master *) urang $ npm --version
6.2.0
bahn (master *) urang $ node-gyp --version
v3.8.0

bahn (master *) urang $ npm install imagesearch

> imagesearch@0.0.6 install /Users/bahn/Projects/urang/node_modules/imagesearch
> node-gyp rebuild

  CXX(target) Release/obj.target/search/src/search.o
../src/search.cc:15:28: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Search(const Arguments& args) {
                           ^~~~~~~~~
                           v8::internal::Arguments
/Users/bahn/.node-gyp/10.8.0/include/node/v8.h:144:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/search.cc:16:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/bahn/.node-gyp/10.8.0/include/node/v8.h:883:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/search.cc:18:34: error: no member named 'New' in 'v8::String'
    Local<String> rows = String::New("rows");
                         ~~~~~~~~^
../src/search.cc:19:34: error: no member named 'New' in 'v8::String'
    Local<String> cols = String::New("cols");
                         ~~~~~~~~^
../src/search.cc:20:34: error: no member named 'New' in 'v8::String'
    Local<String> data = String::New("data");
                         ~~~~~~~~^
../src/search.cc:21:38: error: no member named 'New' in 'v8::String'
    Local<String> channels = String::New("channels");
                             ~~~~~~~~^
../src/search.cc:24:55: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    Handle<Object> matrix1 = Handle<Object>::Cast(args[0]);
                                                  ~~~~^~
../src/search.cc:25:55: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    Handle<Object> matrix2 = Handle<Object>::Cast(args[1]);
                                                  ~~~~^~
../src/search.cc:27:45: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    const unsigned int colorTolerance = args[2]->IsNumber() ? args[2]->Int32Value() : 0;
                                        ~~~~^~
../src/search.cc:27:67: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    const unsigned int colorTolerance = args[2]->IsNumber() ? args[2]->Int32Value() : 0;
                                                              ~~~~^~
../src/search.cc:28:45: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    const unsigned int pixelTolerance = args[3]->IsNumber() ? args[3]->Int32Value() : 0;
                                        ~~~~^~
../src/search.cc:28:67: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    const unsigned int pixelTolerance = args[3]->IsNumber() ? args[3]->Int32Value() : 0;
                                                              ~~~~^~
../src/search.cc:30:89: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    Persistent<Function> callback = Persistent<Function>::New(Local<Function>::Cast(args[4]));
                                                                                    ~~~~^~
../src/search.cc:30:59: error: 'New' is a private member of 'v8::PersistentBase<v8::Function>'
    Persistent<Function> callback = Persistent<Function>::New(Local<Function>::Cast(args[4]));
                                                          ^
/Users/bahn/.node-gyp/10.8.0/include/node/v8.h:632:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../src/search.cc:34:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Bad argument 'imgMatrix'")));
                                                   ~~~~~~~~^
../src/search.cc:38:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Bad argument 'tplMatrix'")));
                                                   ~~~~~~~~^
../src/search.cc:52:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Bad number of channels")));
                                                   ~~~~~~~~^
../src/search.cc:56:60: error: no member named 'New' in 'v8::String'
        return ThrowException(Exception::TypeError(String::New("Channel mismatch")));
                                                   ~~~~~~~~^
../src/search.cc:65:43: error: no member named 'New' in 'v8::String'
    if (m1Channels != m1Data->Get(String::New("length"))->Uint32Value()) {
                                  ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/search/src/search.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bahn/Projects/urang/node_modules/imagesearch
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imagesearch@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imagesearch@0.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bahn/.npm/_logs/2018-12-12T11_45_01_123Z-debug.log
bahn (master *) urang $

**Comment by monai** [comment]
I have no interest in this project anymore. Feel free to port native bindings to nan or N-API by yourself.
